language: node_js
node_js:
  - "8"
install:
  - npm i
  - npm i codecov
script:
  - npm run cov
after_script:
  - codecov
  - test $TRAVIS_NODE_VERSION = 8 && travis_wait scripts/deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 4ba4f15f2d70
